version : '3'
services:
  php_tar:
    build: ./php
    image: php:latest
    container_name: php_tar
    hostname: "php"
    volumes:
      - ./web_atar_update:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - mysql_tar

  mysql_tar:
    image: mariadb:10.2
    container_name: mysql_tar
    restart: unless-stopped
    tty: true
    ports:
      - "53306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: Djoni!!
      MYSQL_PASSWORD: Djony
      MYSQL_ROOT_PASSWORD: Djony
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx_tar:
    build: ./nginx
    image: nginx:latest
    container_name: nginx_tar
    hostname: "nginx"
    ports:
      - "50:80"
    volumes:
      - ./web_atar_update:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_tar

  phpmyadmin_tar:
    image: phpmyadmin:latest
    container_name: phpmyadmin_tar
    restart: always
    ports:
      - 9100:80
    environment:
      - PMA_ARBITRARY=1
